#include <avr/pgmspace.h>

// libARNetworkAL/Includes/libARNetworkAL/ARNETWORKAL_Manager.h
const uint16_t ARNETWORKAL_MANAGER_DEFAULT_ID_MAX PROGMEM = 256;

// ARNETWORKAL_Frame_t identifiers
const uint8_t BD_NET_CD_NONACK_ID PROGMEM = 10;
const uint8_t BD_NET_CD_ACK_ID PROGMEM = 11;
const uint8_t BD_NET_CD_EMERGENCY_ID PROGMEM = 12;
const uint8_t BD_NET_CD_VIDEO_ACK_ID PROGMEM = 13;
const uint8_t BD_NET_DC_VIDEO_DATA_ID PROGMEM = 125;
const uint8_t BD_NET_DC_EVENT_ID PROGMEM = 126;
const uint8_t BD_NET_DC_NAVDATA_ID PROGMEM = 127;

// eARCOMMANDS_ID_PROJECT
const uint8_t ARCOMMANDS_ID_PROJECT_COMMON PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_PROJECT_ARDRONE3 PROGMEM = 1;

// eARCOMMANDS_ID_ARDRONE3_CLASS
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTING PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_ANIMATIONS PROGMEM = 5;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_CAMERA PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORD PROGMEM = 7;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORDSTATE PROGMEM = 8;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIARECORDEVENT PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSTATE PROGMEM = 4;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORK PROGMEM = 13;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSTATE PROGMEM = 14;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSETTINGS PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTINGSETTINGSSTATE PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_SPEEDSETTINGS PROGMEM = 11;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_SPEEDSETTINGSSTATE PROGMEM = 12;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSETTINGS PROGMEM = 9;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_NETWORKSETTINGSSTATE PROGMEM = 10;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_SETTINGS PROGMEM = 15;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_SETTINGSSTATE PROGMEM = 16;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_DIRECTORMODE PROGMEM = 17;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_DIRECTORMODESTATE PROGMEM = 18;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PICTURESETTINGS PROGMEM = 19;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_PICTURESETTINGSSTATE PROGMEM = 20;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIASTREAMING PROGMEM = 21;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIASTREAMINGSTATE PROGMEM = 22;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_GPSSETTINGS PROGMEM = 23;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_GPSSETTINGSSTATE PROGMEM = 24;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_CAMERASTATE PROGMEM = 25;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_ANTIFLICKERING PROGMEM = 29;
const uint8_t ARCOMMANDS_ID_ARDRONE3_CLASS_ANTIFLICKERINGSTATE PROGMEM = 30;

// eARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_FLATTRIMCHANGED PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_FLYINGSTATECHANGED PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ALERTSTATECHANGED PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_NAVIGATEHOMESTATECHANGED PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_POSITIONCHANGED PROGMEM = 4;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_SPEEDCHANGED PROGMEM = 5;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ATTITUDECHANGED PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_AUTOTAKEOFFMODECHANGED PROGMEM = 7;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_ALTITUDECHANGED PROGMEM = 8;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTINGSTATE_CMD_MAX PROGMEM = 9;

// eARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD;
const uint8_t ARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD_FLIP PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_ARDRONE3_ANIMATIONS_CMD_MAX PROGMEM = 1;

// eARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_LANDED PROGMEM = 0;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_TAKINGOFF PROGMEM = 1;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_HOVERING PROGMEM = 2;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_FLYING PROGMEM = 3;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_LANDING PROGMEM = 4;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_EMERGENCY PROGMEM = 5;
const uint8_t ARCOMMANDS_ARDRONE3_PILOTINGSTATE_FLYINGSTATECHANGED_STATE_MAX PROGMEM = 6;

// eARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION;
const uint8_t ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_FRONT PROGMEM = 0;
const uint8_t ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_BACK PROGMEM = 1;
const uint8_t ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_RIGHT PROGMEM = 2;
const uint8_t ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_LEFT PROGMEM = 3;
const uint8_t ARCOMMANDS_ARDRONE3_ANIMATIONS_FLIP_DIRECTION_MAX PROGMEM = 4;

// eARCOMMANDS_ID_COMMON_CLASS
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_NETWORK PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_NETWORKEVENT PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_SETTINGS PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_SETTINGSSTATE PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_COMMON PROGMEM = 4;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_COMMONSTATE PROGMEM = 5;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_OVERHEAT PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_OVERHEATSTATE PROGMEM = 7;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_CONTROLLERSTATE PROGMEM = 8;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGS PROGMEM = 9;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_WIFISETTINGSSTATE PROGMEM = 10;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_MAVLINK PROGMEM = 11;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_MAVLINKSTATE PROGMEM = 12;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_CALIBRATION PROGMEM = 13;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_CALIBRATIONSTATE PROGMEM = 14;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_CAMERASETTINGSSTATE PROGMEM = 15;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_GPS PROGMEM = 16;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANSTATE PROGMEM = 17;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_FLIGHTPLANEVENT PROGMEM = 19;
const uint8_t ARCOMMANDS_ID_COMMON_CLASS_ARLIBSVERSIONSSTATE PROGMEM = 18;

// eARCOMMANDS_ID_ARDRONE3_PILOTING_CMD
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_FLATTRIM PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_TAKEOFF PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_LANDING PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_EMERGENCY PROGMEM = 4;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_NAVIGATEHOME PROGMEM = 5;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_AUTOTAKEOFFMODE PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_MAX PROGMEM = 7;

// eARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD
const uint8_t ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_PICTURE PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_VIDEO PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_PICTUREV2 PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_VIDEOV2 PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_ARDRONE3_MEDIARECORD_CMD_MAX PROGMEM = 4;

// eARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD
const uint8_t ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_STOP PROGMEM = 0;
const uint8_t ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_START PROGMEM = 1;
const uint8_t ARCOMMANDS_ARDRONE3_MEDIARECORD_VIDEO_RECORD_MAX PROGMEM = 2;

// eARCOMMANDS_ID_COMMON_COMMON_CMD
const uint8_t ARCOMMANDS_ID_COMMON_COMMON_CMD_ALLSTATES PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTDATE PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_COMMON_COMMON_CMD_CURRENTTIME PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_COMMON_COMMON_CMD_REBOOT PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_COMMON_COMMON_CMD_MAX PROGMEM = 4;

// eARCOMMANDS_ID_COMMON_COMMONSTATE_CMD;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_ALLSTATESCHANGED PROGMEM = 0;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_BATTERYSTATECHANGED PROGMEM = 1;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGESTATELISTCHANGED PROGMEM = 2;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOSTATELISTCHANGED PROGMEM = 3;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTDATECHANGED PROGMEM = 4;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_CURRENTTIMECHANGED PROGMEM = 5;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MASSSTORAGEINFOREMAININGLISTCHANGED PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_WIFISIGNALCHANGED PROGMEM = 6;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_SENSORSSTATESLISTCHANGED PROGMEM = 7;
const uint8_t ARCOMMANDS_ID_COMMON_COMMONSTATE_CMD_MAX PROGMEM = 8;

// eARMEDIA_ENCAPSULER_CODEC
const uint8_t CODEC_UNKNNOWN PROGMEM = 0;
const uint8_t CODEC_VLIB PROGMEM = 1;
const uint8_t CODEC_P264 PROGMEM = 2;
const uint8_t CODEC_MPEG4_VISUAL PROGMEM = 3;
const uint8_t CODEC_MPEG4_AVC PROGMEM = 4;
const uint8_t CODEC_MOTION_JPEG PROGMEM = 5;

// eARMEDIA_ENCAPSULER_FRAME_TYPE;
const uint8_t ARMEDIA_ENCAPSULER_FRAME_TYPE_UNKNNOWN PROGMEM = 0;
const uint8_t ARMEDIA_ENCAPSULER_FRAME_TYPE_I_FRAME PROGMEM = 1;
const uint8_t ARMEDIA_ENCAPSULER_FRAME_TYPE_P_FRAME PROGMEM = 2;
const uint8_t ARMEDIA_ENCAPSULER_FRAME_TYPE_JPEG PROGMEM = 3;
const uint8_t ARMEDIA_ENCAPSULER_FRAME_TYPE_MAX PROGMEM = 4;

// eARNETWORK_MANAGER_uint8_tERNAL_BUFFER_ID
const uint8_t ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PING PROGMEM = 0;
const uint8_t ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PONG PROGMEM = 1;
const uint8_t ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_MAX PROGMEM = 3;

// eARNETWORKAL_FRAME_TYPE
const uint8_t ARNETWORKAL_FRAME_TYPE_UNINITIALIZED PROGMEM = 0;
const uint8_t ARNETWORKAL_FRAME_TYPE_ACK PROGMEM = 1;
const uint8_t ARNETWORKAL_FRAME_TYPE_DATA PROGMEM = 2;
const uint8_t ARNETWORKAL_FRAME_TYPE_DATA_LOW_LATENCY PROGMEM = 3;
const uint8_t ARNETWORKAL_FRAME_TYPE_DATA_WITH_ACK PROGMEM = 4;
const uint8_t ARNETWORKAL_FRAME_TYPE_MAX PROGMEM = 5;
